
class SubmissionStatus:
    ACCEPTED = 'AC'
    WRONG_ANSWER = 'WA'
    INTERNAL_ERROR = "IR"
    RUNTIME_ERROR = 'RTE'
    TIME_LIMIT_EXCEEDED = "TLE"
    MEMORY_LIMIT_EXCEEDED = "MLE"
    COMPILATION_ERROR = "CE"
    VALID = "VALID"
    INVALID = "INVALID"
    TYPE_JUDGE_SUBMISSION = "TYPE_JUDGE_SUBMISSION"
    TYPE_VALIDATE_CREATE_ISSUE = "TYPE_VALIDATE_CREATE_ISSUE"


